// SnackStack's own collection of everyday Indian recipes. TheMealDB has very few,
// so these fill the gap. Ingredients use common English names; Hindi names are matched
// through the synonyms in recipes.ts. Spices, oil and ghee are treated as pantry staples.

export type LocalRecipe = {
  slug: string
  name: string
  aka?: string[]
  emoji: string
  course: 'Main' | 'Rice' | 'Breakfast' | 'Side' | 'Bread' | 'Dessert' | 'Drink'
  minutes: number
  veg: boolean
  ingredients: [name: string, measure: string][]
  steps: string[]
}

export const INDIAN_RECIPES: LocalRecipe[] = [
  {
    slug: 'dal-tadka',
    name: 'Dal Tadka',
    aka: ['Toor dal', 'Arhar dal'],
    emoji: '🍲',
    course: 'Main',
    minutes: 40,
    veg: true,
    ingredients: [
      ['Toor dal', '1 cup'],
      ['Onion', '1'],
      ['Tomato', '2'],
      ['Garlic', '4 cloves'],
      ['Ginger', '1 inch'],
      ['Green chili', '2'],
      ['Lemon', '½'],
      ['Cilantro', 'a handful'],
      ['Ghee', '2 tbsp'],
      ['Cumin seeds', '1 tsp'],
      ['Turmeric', '½ tsp'],
      ['Red chili powder', '1 tsp'],
      ['Asafoetida', 'a pinch'],
      ['Salt', 'to taste'],
    ],
    steps: [
      'Rinse the dal and pressure-cook it with 3 cups of water, the turmeric and salt for 4 to 5 whistles (or simmer for about 40 minutes) until completely soft. Whisk it smooth.',
      'Heat the ghee, add the cumin seeds and asafoetida. When the cumin sizzles, add the chopped garlic, ginger and green chili and fry for 30 seconds.',
      'Add the chopped onion and cook until golden, then the tomatoes and chili powder. Cook until the tomatoes break down and the ghee separates.',
      'Pour in the cooked dal, add water to the thickness you like, and simmer for 5 minutes.',
      'Finish with lemon juice and chopped cilantro. Serve with rice or roti.',
    ],
  },
  {
    slug: 'moong-dal',
    name: 'Moong Dal',
    aka: ['Mung dal', 'Yellow dal'],
    emoji: '🥣',
    course: 'Main',
    minutes: 30,
    veg: true,
    ingredients: [
      ['Moong dal', '1 cup'],
      ['Onion', '1 small'],
      ['Tomato', '1'],
      ['Garlic', '3 cloves'],
      ['Ginger', '1 inch'],
      ['Green chili', '1'],
      ['Cilantro', 'a handful'],
      ['Ghee', '1 tbsp'],
      ['Cumin seeds', '1 tsp'],
      ['Turmeric', '½ tsp'],
      ['Salt', 'to taste'],
    ],
    steps: [
      'Rinse the dal and cook it with 3 cups of water, the turmeric and salt for about 20 minutes (or 3 whistles) until soft.',
      'Heat the ghee and add the cumin seeds. Once they sizzle, add the garlic, ginger and green chili.',
      'Add the onion and cook until soft, then the tomato until it breaks down.',
      'Stir this into the dal, simmer for 3 minutes and garnish with cilantro.',
    ],
  },
  {
    slug: 'masoor-dal',
    name: 'Masoor Dal',
    aka: ['Red lentil dal'],
    emoji: '🥘',
    course: 'Main',
    minutes: 25,
    veg: true,
    ingredients: [
      ['Red lentils', '1 cup'],
      ['Onion', '1'],
      ['Tomato', '1'],
      ['Garlic', '3 cloves'],
      ['Ginger', '1 inch'],
      ['Green chili', '1'],
      ['Cilantro', 'a handful'],
      ['Oil', '1 tbsp'],
      ['Cumin seeds', '1 tsp'],
      ['Turmeric', '½ tsp'],
      ['Red chili powder', '½ tsp'],
      ['Garam masala', '¼ tsp'],
      ['Salt', 'to taste'],
    ],
    steps: [
      'Rinse the lentils and simmer them in 3 cups of water with the turmeric and salt for about 15 minutes, until they fall apart.',
      'Heat the oil, add the cumin seeds, then the onion, ginger, garlic and green chili. Cook until the onion is golden.',
      'Add the tomato and chili powder and cook until soft.',
      'Stir in the lentils, simmer for 5 minutes, and finish with garam masala and cilantro.',
    ],
  },
  {
    slug: 'chana-masala',
    name: 'Chana Masala',
    aka: ['Chole', 'Chickpea curry'],
    emoji: '🫘',
    course: 'Main',
    minutes: 40,
    veg: true,
    ingredients: [
      ['Chickpeas', '2 cans (or 1 cup dried, soaked and cooked)'],
      ['Onion', '2'],
      ['Tomato', '3'],
      ['Ginger', '1 inch'],
      ['Garlic', '4 cloves'],
      ['Green chili', '2'],
      ['Lemon', '½'],
      ['Cilantro', 'a handful'],
      ['Oil', '3 tbsp'],
      ['Cumin seeds', '1 tsp'],
      ['Coriander powder', '1½ tsp'],
      ['Red chili powder', '1 tsp'],
      ['Turmeric', '½ tsp'],
      ['Garam masala', '1 tsp'],
      ['Salt', 'to taste'],
    ],
    steps: [
      'Heat the oil and add the cumin seeds. Add the finely chopped onions and cook for about 10 minutes until deep golden.',
      'Add the ginger, garlic and green chili and cook for a minute.',
      'Add the chopped tomatoes with the turmeric, coriander and chili powders. Cook until thick and the oil separates.',
      'Add the drained chickpeas, 1 cup of water and salt. Simmer for 15 to 20 minutes, mashing a few chickpeas against the pan to thicken the gravy.',
      'Stir in the garam masala, squeeze over the lemon and top with cilantro. Serve with rice, roti or bhature.',
    ],
  },
  {
    slug: 'rajma',
    name: 'Rajma Masala',
    aka: ['Rajma', 'Rajma chawal', 'Kidney bean curry'],
    emoji: '🫘',
    course: 'Main',
    minutes: 40,
    veg: true,
    ingredients: [
      ['Kidney beans', '2 cans (or 1 cup dried, soaked overnight and cooked)'],
      ['Onion', '2'],
      ['Tomato', '3'],
      ['Ginger', '1 inch'],
      ['Garlic', '4 cloves'],
      ['Green chili', '1'],
      ['Cilantro', 'a handful'],
      ['Oil', '3 tbsp'],
      ['Cumin seeds', '1 tsp'],
      ['Coriander powder', '1½ tsp'],
      ['Red chili powder', '1 tsp'],
      ['Turmeric', '½ tsp'],
      ['Garam masala', '1 tsp'],
      ['Kasuri methi', '1 tsp'],
      ['Salt', 'to taste'],
    ],
    steps: [
      'Heat the oil, add the cumin seeds, then the finely chopped onions. Cook until golden brown.',
      'Add the ginger, garlic and green chili, then the puréed tomatoes and powdered spices. Cook until thick and the oil separates.',
      'Add the drained kidney beans, 2 cups of water and salt. Simmer for 20 minutes, mashing some beans to make the gravy creamy.',
      'Crush the kasuri methi between your palms over the pot, add the garam masala and cilantro. Serve with steamed rice.',
    ],
  },
  {
    slug: 'kadhi',
    name: 'Punjabi Kadhi',
    aka: ['Kadhi'],
    emoji: '🥛',
    course: 'Main',
    minutes: 35,
    veg: true,
    ingredients: [
      ['Yogurt', '1 cup'],
      ['Gram flour', '¼ cup'],
      ['Onion', '1'],
      ['Ginger', '1 inch'],
      ['Green chili', '1'],
      ['Curry leaves', '8'],
      ['Oil', '1 tbsp'],
      ['Mustard seeds', '½ tsp'],
      ['Cumin seeds', '½ tsp'],
      ['Fenugreek seeds', '¼ tsp'],
      ['Turmeric', '½ tsp'],
      ['Red chili powder', '½ tsp'],
      ['Asafoetida', 'a pinch'],
      ['Salt', 'to taste'],
    ],
    steps: [
      'Whisk the yogurt, gram flour, turmeric, chili powder and salt with 3 cups of water until there are no lumps.',
      'Heat the oil and add the mustard, cumin and fenugreek seeds, the asafoetida and the curry leaves.',
      'Add the sliced onion, ginger and green chili and cook until soft.',
      'Pour in the yogurt mixture and keep stirring until it comes to a boil, so it doesn’t split.',
      'Simmer on low for 20 minutes, stirring now and then, until it thickens. Serve with rice.',
    ],
  },
  {
    slug: 'sambar',
    name: 'Sambar',
    aka: ['Sambhar'],
    emoji: '🍛',
    course: 'Main',
    minutes: 45,
    veg: true,
    ingredients: [
      ['Toor dal', '¾ cup'],
      ['Mixed vegetables', '2 cups (drumstick, carrot, pumpkin, okra, eggplant)'],
      ['Onion', '1'],
      ['Tomato', '1'],
      ['Tamarind', '1 tbsp paste'],
      ['Sambar powder', '2 tbsp'],
      ['Curry leaves', '10'],
      ['Cilantro', 'a handful'],
      ['Oil', '1 tbsp'],
      ['Mustard seeds', '1 tsp'],
      ['Dried red chilies', '2'],
      ['Turmeric', '½ tsp'],
      ['Asafoetida', 'a pinch'],
      ['Salt', 'to taste'],
    ],
    steps: [
      'Cook the dal with the turmeric and plenty of water until mushy, then mash it.',
      'Boil the vegetables, onion and tomato in 2 cups of water with the tamarind and salt until tender.',
      'Stir in the sambar powder and the mashed dal and simmer for 10 minutes.',
      'Heat the oil and fry the mustard seeds, dried chilies, curry leaves and asafoetida. Pour this over the sambar.',
      'Add cilantro and serve with rice, idli or dosa.',
    ],
  },
  {
    slug: 'rasam',
    name: 'Rasam',
    aka: ['Tomato rasam'],
    emoji: '🍵',
    course: 'Main',
    minutes: 25,
    veg: true,
    ingredients: [
      ['Tomato', '2'],
      ['Tamarind', '1 tsp paste'],
      ['Toor dal', '¼ cup, cooked (optional)'],
      ['Garlic', '4 cloves'],
      ['Curry leaves', '8'],
      ['Cilantro', 'a handful'],
      ['Ghee', '1 tsp'],
      ['Black pepper', '1 tsp'],
      ['Cumin seeds', '1 tsp'],
      ['Mustard seeds', '½ tsp'],
      ['Dried red chilies', '1'],
      ['Turmeric', '¼ tsp'],
      ['Asafoetida', 'a pinch'],
      ['Salt', 'to taste'],
    ],
    steps: [
      'Coarsely crush the black pepper, cumin and garlic.',
      'Boil the chopped tomatoes with the tamarind, 2 cups of water, turmeric, salt and the crushed mix for 10 minutes.',
      'Add the mashed dal and 1 more cup of water. Heat until frothy, without boiling hard.',
      'Fry the mustard seeds, dried chili, curry leaves and asafoetida in the ghee and pour over. Add cilantro. Drink it as soup or mix with rice.',
    ],
  },
  {
    slug: 'palak-paneer',
    name: 'Palak Paneer',
    aka: ['Spinach paneer'],
    emoji: '🥬',
    course: 'Main',
    minutes: 35,
    veg: true,
    ingredients: [
      ['Spinach', '1 large bunch (about 300 g)'],
      ['Paneer', '200 g'],
      ['Onion', '1'],
      ['Tomato', '1'],
      ['Garlic', '4 cloves'],
      ['Ginger', '1 inch'],
      ['Green chili', '2'],
      ['Cream', '2 tbsp'],
      ['Ghee', '2 tbsp'],
      ['Cumin seeds', '1 tsp'],
      ['Garam masala', '½ tsp'],
      ['Salt', 'to taste'],
    ],
    steps: [
      'Blanch the spinach in boiling water for 2 minutes, then plunge it into ice water to keep it green. Blend with the green chilies into a smooth purée.',
      'Heat the ghee, add the cumin seeds, then the onion. Cook until golden.',
      'Add the ginger and garlic, then the tomato, and cook until soft.',
      'Add the spinach purée and salt and simmer for 5 minutes.',
      'Add the paneer cubes, garam masala and cream and simmer for 3 minutes. Serve with roti or naan.',
    ],
  },
  {
    slug: 'paneer-butter-masala',
    name: 'Paneer Butter Masala',
    aka: ['Paneer makhani'],
    emoji: '🧈',
    course: 'Main',
    minutes: 35,
    veg: true,
    ingredients: [
      ['Paneer', '250 g'],
      ['Tomato', '4'],
      ['Onion', '1'],
      ['Cashews', '10'],
      ['Butter', '2 tbsp'],
      ['Cream', '¼ cup'],
      ['Ginger', '1 inch'],
      ['Garlic', '3 cloves'],
      ['Green chili', '1'],
      ['Kashmiri red chili powder', '1 tsp'],
      ['Garam masala', '½ tsp'],
      ['Kasuri methi', '1 tsp'],
      ['Sugar', '1 tsp'],
      ['Salt', 'to taste'],
    ],
    steps: [
      'Simmer the chopped tomatoes, onion, cashews, ginger, garlic and green chili with ½ cup of water for 10 minutes. Cool slightly and blend until very smooth.',
      'Melt the butter, add the purée and chili powder, and simmer for 10 minutes until thick.',
      'Stir in the cream, garam masala, sugar, salt and the crushed kasuri methi.',
      'Add the paneer cubes and simmer for 3 minutes. Serve with naan or jeera rice.',
    ],
  },
  {
    slug: 'kadai-paneer',
    name: 'Kadai Paneer',
    emoji: '🫑',
    course: 'Main',
    minutes: 30,
    veg: true,
    ingredients: [
      ['Paneer', '250 g'],
      ['Capsicum', '2'],
      ['Onion', '2'],
      ['Tomato', '3'],
      ['Ginger', '1 inch'],
      ['Garlic', '3 cloves'],
      ['Cilantro', 'a handful'],
      ['Oil', '2 tbsp'],
      ['Coriander seeds', '1 tbsp'],
      ['Dried red chilies', '3'],
      ['Garam masala', '½ tsp'],
      ['Kasuri methi', '1 tsp'],
      ['Salt', 'to taste'],
    ],
    steps: [
      'Dry-roast the coriander seeds and dried chilies until fragrant, then grind them coarsely. This is the kadai masala.',
      'Sauté 1 onion and the capsicum, cut into squares, in a little oil for 3 minutes. Set aside.',
      'In the remaining oil, cook the other onion (chopped), the ginger and garlic, then the tomatoes until thick.',
      'Add the kadai masala, then the paneer, the sautéed onion and capsicum, kasuri methi, garam masala and salt. Toss for 3 minutes and top with cilantro.',
    ],
  },
  {
    slug: 'aloo-gobi',
    name: 'Aloo Gobi',
    aka: ['Potato cauliflower'],
    emoji: '🥔',
    course: 'Main',
    minutes: 30,
    veg: true,
    ingredients: [
      ['Cauliflower', '1 small'],
      ['Potato', '2'],
      ['Onion', '1'],
      ['Tomato', '1'],
      ['Ginger', '1 inch'],
      ['Green chili', '1'],
      ['Cilantro', 'a handful'],
      ['Oil', '2 tbsp'],
      ['Cumin seeds', '1 tsp'],
      ['Turmeric', '½ tsp'],
      ['Coriander powder', '1 tsp'],
      ['Red chili powder', '½ tsp'],
      ['Garam masala', '½ tsp'],
      ['Salt', 'to taste'],
    ],
    steps: [
      'Heat the oil, add the cumin seeds, then the onion, ginger and green chili. Cook until the onion softens.',
      'Add the potato cubes and cauliflower florets with the turmeric and salt. Toss, cover and cook on low for 10 minutes, stirring now and then.',
      'Add the tomato, coriander and chili powders and cook uncovered for about 10 minutes until tender.',
      'Finish with garam masala and cilantro. Serve with roti or dal and rice.',
    ],
  },
  {
    slug: 'aloo-matar',
    name: 'Aloo Matar',
    aka: ['Potato peas curry'],
    emoji: '🥔',
    course: 'Main',
    minutes: 30,
    veg: true,
    ingredients: [
      ['Potato', '3'],
      ['Peas', '1 cup'],
      ['Onion', '1'],
      ['Tomato', '2'],
      ['Ginger', '1 inch'],
      ['Garlic', '3 cloves'],
      ['Green chili', '1'],
      ['Cilantro', 'a handful'],
      ['Oil', '2 tbsp'],
      ['Cumin seeds', '1 tsp'],
      ['Turmeric', '½ tsp'],
      ['Coriander powder', '1 tsp'],
      ['Red chili powder', '1 tsp'],
      ['Garam masala', '½ tsp'],
      ['Salt', 'to taste'],
    ],
    steps: [
      'Heat the oil, add the cumin seeds, then the onion. Cook until golden, then add the ginger, garlic and green chili.',
      'Add the tomatoes and powdered spices and cook until thick.',
      'Add the potato cubes, peas, salt and 2 cups of water. Simmer for 15 minutes (or 2 whistles in a pressure cooker) until the potatoes are soft.',
      'Mash a few pieces of potato to thicken the gravy. Add garam masala and cilantro.',
    ],
  },
  {
    slug: 'jeera-aloo',
    name: 'Jeera Aloo',
    aka: ['Cumin potatoes'],
    emoji: '🥔',
    course: 'Side',
    minutes: 20,
    veg: true,
    ingredients: [
      ['Potato', '4, boiled'],
      ['Green chili', '2'],
      ['Ginger', '1 inch'],
      ['Lemon', '½'],
      ['Cilantro', 'a handful'],
      ['Oil', '2 tbsp'],
      ['Cumin seeds', '1½ tsp'],
      ['Turmeric', '¼ tsp'],
      ['Red chili powder', '½ tsp'],
      ['Coriander powder', '1 tsp'],
      ['Salt', 'to taste'],
    ],
    steps: [
      'Peel the boiled potatoes and cut them into cubes.',
      'Heat the oil and add the cumin seeds. When they turn brown, add the ginger and green chili.',
      'Add the potatoes, the powdered spices and salt. Toss on medium heat for 5 minutes until lightly crisp.',
      'Squeeze over the lemon and add cilantro.',
    ],
  },
  {
    slug: 'bhindi-masala',
    name: 'Bhindi Masala',
    aka: ['Okra masala'],
    emoji: '🥒',
    course: 'Main',
    minutes: 25,
    veg: true,
    ingredients: [
      ['Okra', '300 g'],
      ['Onion', '2'],
      ['Tomato', '1'],
      ['Lemon', '½'],
      ['Oil', '3 tbsp'],
      ['Cumin seeds', '1 tsp'],
      ['Turmeric', '½ tsp'],
      ['Coriander powder', '1 tsp'],
      ['Red chili powder', '1 tsp'],
      ['Garam masala', '½ tsp'],
      ['Salt', 'to taste'],
    ],
    steps: [
      'Wash the okra and dry it completely before cutting into 1-inch pieces. Dry okra won’t turn slimy.',
      'Cook the okra in 2 tbsp of oil, uncovered, on medium heat for 8 to 10 minutes until it’s no longer sticky. Set aside.',
      'In the remaining oil, add the cumin seeds, then the sliced onions until golden, then the tomato and powdered spices.',
      'Add the okra and salt, toss for 3 minutes and finish with lemon juice.',
    ],
  },
  {
    slug: 'mixed-veg',
    name: 'Mixed Vegetable Curry',
    aka: ['Mix veg', 'Sabzi'],
    emoji: '🥕',
    course: 'Main',
    minutes: 35,
    veg: true,
    ingredients: [
      ['Mixed vegetables', '3 cups (carrot, beans, peas, potato, cauliflower)'],
      ['Onion', '1'],
      ['Tomato', '2'],
      ['Ginger', '1 inch'],
      ['Garlic', '3 cloves'],
      ['Green chili', '1'],
      ['Cilantro', 'a handful'],
      ['Oil', '2 tbsp'],
      ['Cumin seeds', '1 tsp'],
      ['Turmeric', '½ tsp'],
      ['Coriander powder', '1 tsp'],
      ['Red chili powder', '1 tsp'],
      ['Garam masala', '½ tsp'],
      ['Salt', 'to taste'],
    ],
    steps: [
      'Heat the oil, add the cumin seeds, then the onion. Cook until golden, then add the ginger, garlic and green chili.',
      'Add the tomatoes and powdered spices and cook until the oil separates.',
      'Add the vegetables, salt and 1 cup of water. Cover and simmer for 12 to 15 minutes until tender.',
      'Add garam masala and cilantro. Serve with roti or rice.',
    ],
  },
  {
    slug: 'lauki-sabzi',
    name: 'Lauki Sabzi',
    aka: ['Bottle gourd curry', 'Dudhi'],
    emoji: '🥒',
    course: 'Main',
    minutes: 25,
    veg: true,
    ingredients: [
      ['Bottle gourd', '1 medium'],
      ['Tomato', '1'],
      ['Green chili', '1'],
      ['Ginger', '1 inch'],
      ['Cilantro', 'a handful'],
      ['Oil', '1 tbsp'],
      ['Cumin seeds', '1 tsp'],
      ['Turmeric', '½ tsp'],
      ['Coriander powder', '1 tsp'],
      ['Asafoetida', 'a pinch'],
      ['Salt', 'to taste'],
    ],
    steps: [
      'Peel the bottle gourd and cut it into small cubes.',
      'Heat the oil, add the cumin seeds and asafoetida, then the ginger and green chili.',
      'Add the tomato, turmeric and coriander powder and cook for 2 minutes.',
      'Add the bottle gourd and salt, cover and cook on low for 12 to 15 minutes until soft (it releases its own water). Add cilantro.',
    ],
  },
  {
    slug: 'dum-aloo',
    name: 'Dum Aloo',
    emoji: '🥔',
    course: 'Main',
    minutes: 40,
    veg: true,
    ingredients: [
      ['Baby potatoes', '500 g'],
      ['Yogurt', '½ cup'],
      ['Onion', '1'],
      ['Tomato', '2'],
      ['Ginger', '1 inch'],
      ['Garlic', '3 cloves'],
      ['Cilantro', 'a handful'],
      ['Oil', '3 tbsp'],
      ['Cumin seeds', '1 tsp'],
      ['Kashmiri red chili powder', '1½ tsp'],
      ['Turmeric', '½ tsp'],
      ['Coriander powder', '1 tsp'],
      ['Garam masala', '½ tsp'],
      ['Salt', 'to taste'],
    ],
    steps: [
      'Boil the baby potatoes until just tender, peel them, prick them with a fork and fry until golden. Set aside.',
      'In the same oil, add the cumin seeds, then the onion until golden, then the ginger, garlic and tomatoes. Cook until thick.',
      'Lower the heat. Whisk the yogurt with the chili powder and add it slowly while stirring, so it doesn’t split.',
      'Add the potatoes, the other spices, salt and ½ cup of water. Cover and cook on low for 10 minutes. Add cilantro.',
    ],
  },
  {
    slug: 'cabbage-poriyal',
    name: 'Cabbage Poriyal',
    aka: ['Cabbage thoran', 'Patta gobi'],
    emoji: '🥬',
    course: 'Side',
    minutes: 20,
    veg: true,
    ingredients: [
      ['Cabbage', '½ head'],
      ['Grated coconut', '¼ cup'],
      ['Green chili', '1'],
      ['Curry leaves', '8'],
      ['Urad dal', '1 tsp'],
      ['Oil', '1 tbsp'],
      ['Mustard seeds', '1 tsp'],
      ['Dried red chilies', '2'],
      ['Turmeric', '¼ tsp'],
      ['Salt', 'to taste'],
    ],
    steps: [
      'Finely shred the cabbage.',
      'Heat the oil, add the mustard seeds and urad dal and fry until the dal turns golden. Add the dried chilies, green chili and curry leaves.',
      'Add the cabbage, turmeric and salt. Cook uncovered on medium heat for 6 to 8 minutes, stirring, until just tender.',
      'Stir in the coconut and serve with rice and sambar.',
    ],
  },
  {
    slug: 'egg-curry',
    name: 'Egg Curry',
    aka: ['Anda curry'],
    emoji: '🥚',
    course: 'Main',
    minutes: 30,
    veg: false,
    ingredients: [
      ['Eggs', '6'],
      ['Onion', '2'],
      ['Tomato', '2'],
      ['Ginger', '1 inch'],
      ['Garlic', '4 cloves'],
      ['Green chili', '1'],
      ['Cilantro', 'a handful'],
      ['Oil', '3 tbsp'],
      ['Cumin seeds', '1 tsp'],
      ['Turmeric', '½ tsp'],
      ['Red chili powder', '1 tsp'],
      ['Coriander powder', '1½ tsp'],
      ['Garam masala', '½ tsp'],
      ['Salt', 'to taste'],
    ],
    steps: [
      'Hard-boil the eggs for 10 minutes, peel them and make shallow slits. Fry them briefly in 1 tbsp of oil with a pinch of turmeric and chili powder. Set aside.',
      'In the remaining oil, add the cumin seeds, then the onions until golden brown, then the ginger, garlic and green chili.',
      'Add the tomatoes and powdered spices and cook until the oil separates.',
      'Add 1½ cups of water and salt, bring to a boil, add the eggs and simmer for 5 to 8 minutes. Finish with garam masala and cilantro.',
    ],
  },
  {
    slug: 'egg-bhurji',
    name: 'Egg Bhurji',
    aka: ['Anda bhurji', 'Indian scrambled eggs'],
    emoji: '🍳',
    course: 'Breakfast',
    minutes: 15,
    veg: false,
    ingredients: [
      ['Eggs', '4'],
      ['Onion', '1'],
      ['Tomato', '1'],
      ['Green chili', '1'],
      ['Butter', '1 tbsp'],
      ['Cilantro', 'a handful'],
      ['Turmeric', '¼ tsp'],
      ['Red chili powder', '½ tsp'],
      ['Garam masala', '¼ tsp'],
      ['Salt', 'to taste'],
    ],
    steps: [
      'Melt the butter, add the chopped onion and green chili and cook until soft.',
      'Add the tomato, turmeric, chili powder and salt and cook for 2 minutes.',
      'Pour in the beaten eggs and stir gently on low heat until just set.',
      'Sprinkle over the garam masala and cilantro. Serve with toast or pav.',
    ],
  },
  {
    slug: 'chicken-curry',
    name: 'Chicken Curry',
    aka: ['Home-style chicken curry', 'Murgh curry'],
    emoji: '🍗',
    course: 'Main',
    minutes: 50,
    veg: false,
    ingredients: [
      ['Chicken', '750 g, bone-in pieces'],
      ['Onion', '3'],
      ['Tomato', '2'],
      ['Yogurt', '½ cup'],
      ['Ginger', '1 inch'],
      ['Garlic', '6 cloves'],
      ['Green chili', '2'],
      ['Cilantro', 'a handful'],
      ['Oil', '4 tbsp'],
      ['Bay leaf', '1'],
      ['Cloves', '3'],
      ['Cardamom', '2'],
      ['Cinnamon', '1 inch'],
      ['Turmeric', '½ tsp'],
      ['Red chili powder', '1½ tsp'],
      ['Coriander powder', '2 tsp'],
      ['Garam masala', '1 tsp'],
      ['Salt', 'to taste'],
    ],
    steps: [
      'Mix the chicken with the yogurt, turmeric, half the chili powder and salt. Leave for 30 minutes if you have time.',
      'Heat the oil with the bay leaf, cloves, cardamom and cinnamon. Add the sliced onions and cook for 12 minutes until deep brown.',
      'Add the ginger, garlic and green chili paste, then the tomatoes and the remaining powdered spices. Cook until the oil separates.',
      'Add the chicken and cook on high for 5 minutes, then add 1 cup of water, cover and simmer for 25 minutes until tender.',
      'Finish with garam masala and cilantro. Serve with rice or roti.',
    ],
  },
  {
    slug: 'butter-chicken',
    name: 'Butter Chicken',
    aka: ['Murgh makhani'],
    emoji: '🍗',
    course: 'Main',
    minutes: 50,
    veg: false,
    ingredients: [
      ['Chicken', '500 g, boneless'],
      ['Yogurt', '½ cup'],
      ['Tomato', '5'],
      ['Butter', '3 tbsp'],
      ['Cream', '½ cup'],
      ['Cashews', '10'],
      ['Ginger', '1 inch'],
      ['Garlic', '4 cloves'],
      ['Lemon', '½'],
      ['Kashmiri red chili powder', '2 tsp'],
      ['Garam masala', '1 tsp'],
      ['Kasuri methi', '1 tsp'],
      ['Sugar', '1 tsp'],
      ['Salt', 'to taste'],
    ],
    steps: [
      'Marinate the chicken in the yogurt, lemon juice, 1 tsp chili powder, ½ tsp garam masala, half the ginger and garlic, and salt for at least 30 minutes.',
      'Sear or grill the chicken until lightly charred and cooked through.',
      'Simmer the tomatoes, cashews and the rest of the ginger and garlic for 15 minutes, then blend until smooth.',
      'Melt the butter, add the sauce and the remaining chili powder and simmer for 10 minutes.',
      'Stir in the cream, crushed kasuri methi, sugar and the rest of the garam masala. Add the chicken and simmer for 5 minutes. Serve with naan.',
    ],
  },
  {
    slug: 'keema-matar',
    name: 'Keema Matar',
    aka: ['Keema', 'Minced meat with peas'],
    emoji: '🍖',
    course: 'Main',
    minutes: 35,
    veg: false,
    ingredients: [
      ['Minced meat', '500 g (lamb, goat or chicken)'],
      ['Peas', '1 cup'],
      ['Onion', '2'],
      ['Tomato', '2'],
      ['Yogurt', '2 tbsp'],
      ['Ginger', '1 inch'],
      ['Garlic', '4 cloves'],
      ['Green chili', '2'],
      ['Cilantro', 'a handful'],
      ['Oil', '3 tbsp'],
      ['Cumin seeds', '1 tsp'],
      ['Bay leaf', '1'],
      ['Turmeric', '½ tsp'],
      ['Red chili powder', '1 tsp'],
      ['Coriander powder', '1½ tsp'],
      ['Garam masala', '1 tsp'],
      ['Salt', 'to taste'],
    ],
    steps: [
      'Heat the oil with the cumin seeds and bay leaf. Add the onions and cook until golden.',
      'Add the ginger, garlic and green chili, then the mince. Cook on high, breaking it up, until it’s no longer pink.',
      'Add the tomatoes, yogurt, powdered spices and salt. Cook until the oil separates.',
      'Add the peas and ½ cup of water, cover and simmer for 15 minutes. Finish with garam masala and cilantro. Serve with pav or roti.',
    ],
  },
  {
    slug: 'fish-curry',
    name: 'Coconut Fish Curry',
    aka: ['Meen curry', 'Machli curry'],
    emoji: '🐟',
    course: 'Main',
    minutes: 35,
    veg: false,
    ingredients: [
      ['Fish', '500 g firm white fillets'],
      ['Coconut milk', '1 can'],
      ['Onion', '1'],
      ['Tomato', '1'],
      ['Ginger', '1 inch'],
      ['Garlic', '4 cloves'],
      ['Green chili', '2'],
      ['Curry leaves', '10'],
      ['Tamarind', '1 tbsp paste'],
      ['Oil', '2 tbsp'],
      ['Mustard seeds', '1 tsp'],
      ['Turmeric', '½ tsp'],
      ['Red chili powder', '1 tsp'],
      ['Coriander powder', '1½ tsp'],
      ['Salt', 'to taste'],
    ],
    steps: [
      'Rub the fish with salt and a pinch of turmeric.',
      'Heat the oil, add the mustard seeds and curry leaves, then the onion, ginger, garlic and green chili. Cook until soft.',
      'Add the tomato and powdered spices and cook for 3 minutes. Stir in the tamarind and coconut milk with ½ cup of water and bring to a gentle simmer.',
      'Slide in the fish and simmer, without stirring, for 6 to 8 minutes until it flakes. Serve with rice.',
    ],
  },
  {
    slug: 'jeera-rice',
    name: 'Jeera Rice',
    aka: ['Cumin rice'],
    emoji: '🍚',
    course: 'Rice',
    minutes: 25,
    veg: true,
    ingredients: [
      ['Basmati rice', '1 cup'],
      ['Cilantro', 'to garnish'],
      ['Ghee', '1 tbsp'],
      ['Cumin seeds', '1½ tsp'],
      ['Bay leaf', '1'],
      ['Salt', 'to taste'],
    ],
    steps: [
      'Rinse the rice until the water runs clear and soak it for 20 minutes. Drain.',
      'Heat the ghee, add the cumin seeds and bay leaf, then the rice. Stir gently for a minute.',
      'Add 1¾ cups of water and salt. Bring to a boil, cover and cook on the lowest heat for 12 minutes.',
      'Rest for 5 minutes without opening, then fluff with a fork and add cilantro.',
    ],
  },
  {
    slug: 'veg-pulao',
    name: 'Vegetable Pulao',
    aka: ['Veg pulav'],
    emoji: '🍚',
    course: 'Rice',
    minutes: 35,
    veg: true,
    ingredients: [
      ['Basmati rice', '1 cup'],
      ['Mixed vegetables', '1½ cups (carrot, peas, beans)'],
      ['Onion', '1'],
      ['Ginger', '1 inch'],
      ['Garlic', '2 cloves'],
      ['Green chili', '1'],
      ['Ghee', '2 tbsp'],
      ['Cumin seeds', '1 tsp'],
      ['Bay leaf', '1'],
      ['Cloves', '3'],
      ['Cardamom', '2'],
      ['Cinnamon', '1 inch'],
      ['Salt', 'to taste'],
    ],
    steps: [
      'Rinse and soak the rice for 20 minutes. Drain.',
      'Heat the ghee with the cumin seeds and whole spices. Add the sliced onion and cook until golden, then the ginger, garlic and green chili.',
      'Add the vegetables and cook for 2 minutes, then the rice. Stir gently for a minute.',
      'Add 2 cups of water and salt, bring to a boil, cover and cook on low for 12 minutes. Rest for 5 minutes and fluff.',
    ],
  },
  {
    slug: 'khichdi',
    name: 'Khichdi',
    aka: ['Moong dal khichdi'],
    emoji: '🥣',
    course: 'Rice',
    minutes: 30,
    veg: true,
    ingredients: [
      ['Rice', '½ cup'],
      ['Moong dal', '½ cup'],
      ['Ginger', '½ inch'],
      ['Ghee', '1 tbsp'],
      ['Cumin seeds', '1 tsp'],
      ['Turmeric', '½ tsp'],
      ['Asafoetida', 'a pinch'],
      ['Salt', 'to taste'],
    ],
    steps: [
      'Rinse the rice and dal together.',
      'Heat the ghee in a pressure cooker, add the cumin seeds, asafoetida and grated ginger.',
      'Add the rice and dal, turmeric, salt and 4 cups of water. Cook for 3 to 4 whistles (or simmer for 25 minutes) until soft and porridge-like.',
      'Serve hot with a spoon of ghee, yogurt and pickle.',
    ],
  },
  {
    slug: 'lemon-rice',
    name: 'Lemon Rice',
    aka: ['Chitranna', 'Nimbu chawal'],
    emoji: '🍋',
    course: 'Rice',
    minutes: 15,
    veg: true,
    ingredients: [
      ['Cooked rice', '3 cups'],
      ['Lemon', '1'],
      ['Peanuts', '2 tbsp'],
      ['Green chili', '2'],
      ['Ginger', '½ inch'],
      ['Curry leaves', '10'],
      ['Chana dal', '1 tsp'],
      ['Urad dal', '1 tsp'],
      ['Cilantro', 'a handful'],
      ['Oil', '2 tbsp'],
      ['Mustard seeds', '1 tsp'],
      ['Turmeric', '½ tsp'],
      ['Asafoetida', 'a pinch'],
      ['Salt', 'to taste'],
    ],
    steps: [
      'Spread the cooked rice out to cool so the grains stay separate.',
      'Heat the oil and fry the peanuts until crunchy. Add the mustard seeds, chana dal and urad dal and fry until golden.',
      'Add the green chili, ginger, curry leaves, asafoetida and turmeric.',
      'Add the rice and salt and toss gently. Turn off the heat, squeeze over the lemon and add cilantro.',
    ],
  },
  {
    slug: 'curd-rice',
    name: 'Curd Rice',
    aka: ['Thayir sadam', 'Dahi chawal'],
    emoji: '🍚',
    course: 'Rice',
    minutes: 15,
    veg: true,
    ingredients: [
      ['Cooked rice', '2 cups'],
      ['Yogurt', '1 cup'],
      ['Milk', '¼ cup'],
      ['Ginger', '½ inch'],
      ['Green chili', '1'],
      ['Curry leaves', '8'],
      ['Urad dal', '1 tsp'],
      ['Cilantro', 'a handful'],
      ['Oil', '1 tsp'],
      ['Mustard seeds', '½ tsp'],
      ['Asafoetida', 'a pinch'],
      ['Salt', 'to taste'],
    ],
    steps: [
      'Mash the rice slightly while it’s warm, then let it cool.',
      'Mix in the yogurt, milk, salt, grated ginger and chopped green chili.',
      'Fry the mustard seeds, urad dal, curry leaves and asafoetida in the oil and pour over.',
      'Add cilantro. Serve cool, with pickle.',
    ],
  },
  {
    slug: 'tomato-rice',
    name: 'Tomato Rice',
    aka: ['Thakkali sadam'],
    emoji: '🍅',
    course: 'Rice',
    minutes: 25,
    veg: true,
    ingredients: [
      ['Cooked rice', '3 cups'],
      ['Tomato', '3'],
      ['Onion', '1'],
      ['Ginger', '½ inch'],
      ['Garlic', '3 cloves'],
      ['Green chili', '1'],
      ['Curry leaves', '8'],
      ['Cilantro', 'a handful'],
      ['Oil', '2 tbsp'],
      ['Mustard seeds', '1 tsp'],
      ['Turmeric', '½ tsp'],
      ['Red chili powder', '1 tsp'],
      ['Garam masala', '½ tsp'],
      ['Salt', 'to taste'],
    ],
    steps: [
      'Heat the oil, add the mustard seeds and curry leaves, then the onion, ginger, garlic and green chili.',
      'Add the chopped tomatoes, turmeric, chili powder and salt. Cook until the tomatoes turn into a thick paste.',
      'Add the garam masala and the rice and toss gently until coated. Top with cilantro.',
    ],
  },
  {
    slug: 'chicken-biryani',
    name: 'Chicken Biryani',
    aka: ['Biryani'],
    emoji: '🍛',
    course: 'Rice',
    minutes: 75,
    veg: false,
    ingredients: [
      ['Chicken', '750 g'],
      ['Basmati rice', '2 cups'],
      ['Yogurt', '¾ cup'],
      ['Onion', '3'],
      ['Ginger', '1 inch'],
      ['Garlic', '6 cloves'],
      ['Green chili', '3'],
      ['Mint leaves', 'a handful'],
      ['Cilantro', 'a handful'],
      ['Lemon', '1'],
      ['Ghee', '3 tbsp'],
      ['Oil', '3 tbsp'],
      ['Bay leaf', '2'],
      ['Cloves', '4'],
      ['Cardamom', '4'],
      ['Cinnamon', '1 inch'],
      ['Turmeric', '½ tsp'],
      ['Red chili powder', '1½ tsp'],
      ['Garam masala', '2 tsp'],
      ['Salt', 'to taste'],
    ],
    steps: [
      'Marinate the chicken with the yogurt, ginger-garlic paste, green chili, turmeric, chili powder, garam masala, half the mint and cilantro, lemon juice and salt for at least an hour.',
      'Rinse the rice and soak it for 30 minutes.',
      'Fry the thinly sliced onions in the oil until deep brown and crisp. Keep half aside for the top.',
      'Add the marinated chicken to the pot with the remaining onions and cook for 10 minutes.',
      'Meanwhile, boil the rice in plenty of salted water with the whole spices for 5 minutes until about 70% cooked. Drain.',
      'Layer the rice over the chicken, scatter the fried onions, the rest of the mint and cilantro, and drizzle with ghee.',
      'Cover tightly and cook on the lowest heat for 25 minutes. Rest for 10 minutes, then gently mix from the bottom and serve with raita.',
    ],
  },
  {
    slug: 'poha',
    name: 'Poha',
    aka: ['Kanda poha', 'Flattened rice'],
    emoji: '🍽️',
    course: 'Breakfast',
    minutes: 20,
    veg: true,
    ingredients: [
      ['Flattened rice', '2 cups, thick'],
      ['Onion', '1'],
      ['Potato', '1 small (optional)'],
      ['Peanuts', '2 tbsp'],
      ['Green chili', '2'],
      ['Curry leaves', '8'],
      ['Lemon', '½'],
      ['Cilantro', 'a handful'],
      ['Oil', '2 tbsp'],
      ['Mustard seeds', '1 tsp'],
      ['Turmeric', '½ tsp'],
      ['Sugar', '1 tsp'],
      ['Salt', 'to taste'],
    ],
    steps: [
      'Rinse the poha in a sieve 2 or 3 times, drain, mix in the salt, sugar and turmeric and leave for 5 minutes to soften.',
      'Fry the peanuts in the oil until crunchy and set aside.',
      'Add the mustard seeds, curry leaves and green chili, then the onion (and the diced potato, cooked until tender).',
      'Add the poha and toss gently on low heat for 2 to 3 minutes. Top with the peanuts, lemon juice and cilantro.',
    ],
  },
  {
    slug: 'upma',
    name: 'Upma',
    aka: ['Rava upma', 'Sooji upma'],
    emoji: '🥣',
    course: 'Breakfast',
    minutes: 20,
    veg: true,
    ingredients: [
      ['Semolina', '1 cup'],
      ['Onion', '1'],
      ['Green chili', '2'],
      ['Ginger', '½ inch'],
      ['Curry leaves', '8'],
      ['Urad dal', '1 tsp'],
      ['Mixed vegetables', '½ cup (optional)'],
      ['Cilantro', 'a handful'],
      ['Ghee', '2 tbsp'],
      ['Mustard seeds', '1 tsp'],
      ['Salt', 'to taste'],
    ],
    steps: [
      'Dry-roast the semolina on low heat until fragrant, about 5 minutes. Set aside.',
      'Heat the ghee, add the mustard seeds and urad dal, then the curry leaves, ginger and green chili, then the onion and vegetables.',
      'Pour in 2½ cups of water with salt and bring to a boil.',
      'Lower the heat and add the semolina slowly, stirring all the time so no lumps form. Cover for 2 minutes, then fluff and add cilantro.',
    ],
  },
  {
    slug: 'besan-chilla',
    name: 'Besan Chilla',
    aka: ['Gram flour pancakes', 'Pudla'],
    emoji: '🥞',
    course: 'Breakfast',
    minutes: 20,
    veg: true,
    ingredients: [
      ['Gram flour', '1 cup'],
      ['Onion', '1 small'],
      ['Tomato', '1 small'],
      ['Green chili', '1'],
      ['Cilantro', 'a handful'],
      ['Oil', 'for cooking'],
      ['Turmeric', '¼ tsp'],
      ['Red chili powder', '½ tsp'],
      ['Salt', 'to taste'],
    ],
    steps: [
      'Whisk the gram flour, turmeric, chili powder and salt with about ¾ cup of water into a smooth, pourable batter.',
      'Stir in the finely chopped onion, tomato, green chili and cilantro.',
      'Spread a ladle of batter thinly on a hot oiled pan. Drizzle oil around the edge and cook until golden underneath, then flip and cook the other side.',
      'Serve hot with green chutney or ketchup.',
    ],
  },
  {
    slug: 'aloo-paratha',
    name: 'Aloo Paratha',
    aka: ['Potato flatbread'],
    emoji: '🫓',
    course: 'Bread',
    minutes: 45,
    veg: true,
    ingredients: [
      ['Whole wheat flour', '2 cups'],
      ['Potato', '3, boiled'],
      ['Green chili', '2'],
      ['Ginger', '½ inch'],
      ['Cilantro', 'a handful'],
      ['Ghee', 'for cooking'],
      ['Red chili powder', '½ tsp'],
      ['Garam masala', '½ tsp'],
      ['Salt', 'to taste'],
    ],
    steps: [
      'Knead the flour with a pinch of salt and enough water into a soft dough. Rest it for 20 minutes.',
      'Mash the potatoes with the chopped green chili, ginger, cilantro, chili powder, garam masala and salt.',
      'Roll a ball of dough into a small circle, put a ball of filling in the middle, bring the edges up and seal. Flatten and roll out gently.',
      'Cook on a hot pan, flipping and brushing with ghee, until golden spots appear on both sides. Serve with yogurt and pickle.',
    ],
  },
  {
    slug: 'masala-omelette',
    name: 'Masala Omelette',
    aka: ['Indian omelette'],
    emoji: '🍳',
    course: 'Breakfast',
    minutes: 10,
    veg: false,
    ingredients: [
      ['Eggs', '2'],
      ['Onion', '1 small'],
      ['Tomato', '1 small'],
      ['Green chili', '1'],
      ['Cilantro', 'a little'],
      ['Butter', '1 tsp'],
      ['Turmeric', 'a pinch'],
      ['Red chili powder', 'a pinch'],
      ['Black pepper', 'a pinch'],
      ['Salt', 'to taste'],
    ],
    steps: [
      'Beat the eggs with the finely chopped onion, tomato, green chili, cilantro, the spices and salt.',
      'Melt the butter in a pan, pour in the eggs and cook on medium heat until the bottom sets.',
      'Fold or flip and cook for another minute. Serve with toast.',
    ],
  },
  {
    slug: 'sabudana-khichdi',
    name: 'Sabudana Khichdi',
    aka: ['Sago khichdi'],
    emoji: '⚪',
    course: 'Breakfast',
    minutes: 30,
    veg: true,
    ingredients: [
      ['Sago', '1 cup (sabudana), soaked for 6 hours'],
      ['Potato', '1'],
      ['Peanuts', '½ cup'],
      ['Green chili', '2'],
      ['Curry leaves', '8'],
      ['Lemon', '½'],
      ['Cilantro', 'a handful'],
      ['Ghee', '2 tbsp'],
      ['Cumin seeds', '1 tsp'],
      ['Sugar', '1 tsp'],
      ['Salt', 'to taste'],
    ],
    steps: [
      'Rinse the sago, then soak it in just enough water to cover for 6 hours or overnight, until the pearls are soft and press flat between your fingers.',
      'Dry-roast the peanuts and crush them coarsely.',
      'Heat the ghee, add the cumin seeds, green chili and curry leaves, then the potato cubes. Cook until tender.',
      'Add the drained sago, crushed peanuts, salt and sugar. Stir on low heat for 5 to 7 minutes until the pearls turn translucent. Finish with lemon and cilantro.',
    ],
  },
  {
    slug: 'paneer-bhurji',
    name: 'Paneer Bhurji',
    aka: ['Scrambled paneer'],
    emoji: '🧀',
    course: 'Main',
    minutes: 15,
    veg: true,
    ingredients: [
      ['Paneer', '200 g, crumbled'],
      ['Onion', '1'],
      ['Tomato', '1'],
      ['Green chili', '1'],
      ['Ginger', '½ inch'],
      ['Cilantro', 'a handful'],
      ['Butter', '1 tbsp'],
      ['Cumin seeds', '½ tsp'],
      ['Turmeric', '¼ tsp'],
      ['Red chili powder', '½ tsp'],
      ['Garam masala', '¼ tsp'],
      ['Salt', 'to taste'],
    ],
    steps: [
      'Melt the butter, add the cumin seeds, then the onion, ginger and green chili. Cook until soft.',
      'Add the tomato and spices and cook until mushy.',
      'Add the crumbled paneer and salt and toss for 2 to 3 minutes. Add cilantro and serve with roti or toast.',
    ],
  },
  {
    slug: 'cucumber-raita',
    name: 'Cucumber Raita',
    aka: ['Kheera raita'],
    emoji: '🥒',
    course: 'Side',
    minutes: 10,
    veg: true,
    ingredients: [
      ['Yogurt', '1½ cups'],
      ['Cucumber', '1'],
      ['Mint leaves', 'a few'],
      ['Cumin seeds', '½ tsp, roasted and ground'],
      ['Red chili powder', 'a pinch'],
      ['Salt', 'to taste'],
    ],
    steps: [
      'Whisk the yogurt until smooth.',
      'Grate the cucumber, squeeze out some of the water and stir it in.',
      'Add the roasted cumin, chili powder, chopped mint and salt. Serve chilled with biryani or parathas.',
    ],
  },
  {
    slug: 'rice-kheer',
    name: 'Rice Kheer',
    aka: ['Kheer', 'Payasam', 'Rice pudding'],
    emoji: '🍮',
    course: 'Dessert',
    minutes: 45,
    veg: true,
    ingredients: [
      ['Milk', '1 litre (4 cups)'],
      ['Rice', '¼ cup'],
      ['Almonds', '10'],
      ['Sugar', '⅓ cup'],
      ['Cardamom', '4'],
    ],
    steps: [
      'Rinse the rice and soak it for 20 minutes.',
      'Bring the milk to a boil in a heavy pan, add the rice and simmer on low, stirring often so it doesn’t catch, for 25 to 30 minutes until the rice is soft and the milk thickens.',
      'Add the sugar, crushed cardamom and sliced almonds and cook for 5 more minutes.',
      'Serve warm or chilled.',
    ],
  },
  {
    slug: 'gajar-halwa',
    name: 'Gajar Halwa',
    aka: ['Carrot halwa'],
    emoji: '🥕',
    course: 'Dessert',
    minutes: 50,
    veg: true,
    ingredients: [
      ['Carrots', '500 g, grated'],
      ['Milk', '2 cups'],
      ['Cashews', '10'],
      ['Ghee', '3 tbsp'],
      ['Sugar', '½ cup'],
      ['Cardamom', '4'],
    ],
    steps: [
      'Cook the grated carrots in the milk on medium heat, stirring often, until the milk has evaporated, about 30 minutes.',
      'Add the ghee and sugar and keep cooking for 10 minutes until glossy and pulling away from the pan.',
      'Stir in the crushed cardamom and chopped cashews. Serve warm.',
    ],
  },
  {
    slug: 'roti',
    name: 'Roti',
    aka: ['Chapati', 'Phulka'],
    emoji: '🫓',
    course: 'Bread',
    minutes: 30,
    veg: true,
    ingredients: [
      ['Whole wheat flour', '2 cups'],
      ['Ghee', 'for brushing'],
      ['Water', 'about ¾ cup'],
      ['Salt', 'a pinch'],
    ],
    steps: [
      'Knead the flour, salt and water into a soft dough for 5 minutes. Cover and rest for 20 minutes.',
      'Divide into 8 balls and roll each one thin, about 6 inches across, dusting with flour.',
      'Cook on a hot pan until small bubbles appear, flip and cook for 30 seconds, then press gently with a cloth (or hold over an open flame) so it puffs up.',
      'Brush with ghee and keep wrapped in a cloth so they stay soft.',
    ],
  },
  {
    slug: 'masala-chai',
    name: 'Masala Chai',
    aka: ['Chai', 'Tea'],
    emoji: '☕',
    course: 'Drink',
    minutes: 10,
    veg: true,
    ingredients: [
      ['Milk', '1 cup'],
      ['Tea', '2 tsp loose black tea'],
      ['Ginger', '½ inch'],
      ['Water', '1 cup'],
      ['Sugar', '2 tsp'],
      ['Cardamom', '2'],
    ],
    steps: [
      'Boil the water with the crushed ginger and cardamom for 2 minutes.',
      'Add the tea and boil for 1 minute.',
      'Add the milk and sugar and bring to a boil twice, letting it rise each time.',
      'Strain into cups.',
    ],
  },
]
